server:
  port: 8888

mybatis:
  # 注册mybatis中实体类的别名
  type-aliases-package: com.yw.model
  # 注册映射文件
  mapper-locations: classpath:com/yw/dao/*.xml

spring:
  # 注册数据源
  datasource:
    # 指定数据源类型为Druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: yw@910714

  # 连接Redis服务器
  redis:
    host: 192.168.254.128
    port: 6379
    password:
  # 连接Redis高可用集群
  #  redis:
  #    sentinel:
  #      master: mymaster
  #      nodes:
  #        - 192.168.254.128:26379
  #        - 192.168.254.130:26379
  #        - 192.168.254.132:26379

  # 配置缓存
  cache:
    # 指定缓存类型
    type: redis
    # 指定缓存区域名称
    cache-names: realTimeCache

  # 功能等价于 spring-dubbo 配置文件中的<dubbo:application>
  application:
    name: 11-provider-springboot
  # 指定zk注册中心
  dubbo:
    registry: zookeeper://192.168.254.120:2181
  # zk集群作注册中心
  # registry: zookeeper://192.168.254.128:2181?backup=192.168.254.130:2181,192.168.254.132:2181,192.168.254.129:2181
